version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip"
      - "unzip terraform_1.5.2_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "pwd"

  pre_build:
    commands:
      - echo Chave de acesso- $AWS_ACCESS_KEY_ID
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - python create_s3_bucket.py $ORG-$ACCOUNT_ID-terraform-state
      - aws s3 ls ${ORG}-${ACCOUNT_ID}-terraform-state
      - cd infra
      - terraform init -migrate-state -backend-config="bucket=${ORG}-${ACCOUNT_ID}-terraform-state" -backend-config="key=state/aws/sdlf/generation-json/terraform.tfstate" -backend-config="region=us-east-1"
  build:
    commands:
      - "pwd"
      - terraform fmt --recursive
      - terraform plan -var-file="./_variables/prd.tfvars"
      - terraform apply -auto-approve -var-file="./_variables/prd.tfvars"
      #- terraform destroy -auto-approve -var-file="./_variables/prd.tfvars"
      
  post_build:
    commands:
      - echo Terraform apply completed on `date`

      