name: DemoCICD
on:
  workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Run a one0line script
      run: echo Hello, world!!
      
 deploy-dev:
  runs-on: ubuntu-latest
  environment:
    name: dev
    url: '4insights.net/console'
  needs: build
  steps:
    - name: Run a one0line script
      run: echo Deploy Dev
      
 deploy-prd:
  runs-on: ubuntu-latest
  environment:
    name: prd
    url: '4insights.net'
  needs: deploy-dev
  steps:
    - name: Run a one0line script
      run: echo Deploy Prd
